### ISSUE TITLE
Keyword `Log In` is broken in Plone 4

### ISSUE THREAD

**Issue by pgrunewald** [plone/plone.app.robotframework#107]
The keyword `Log In` is broken for Plone 4.15 (latest one), which should be the release 1.2.1 before dropping support for Plone 4.

The selector used in this keyword does not match. The label there is "Login Name", see [here](https://github.com/plone/Products.CMFPlone/blob/4.3.15/Products/CMFPlone/skins/plone_login/login_form.cpt#L130). The change was introduced with this [commit](https://github.com/plone/plone.app.robotframework/commit/9f80a05edceb71ae91e6da4dc69d353f4763863c).

**Comment by idgserpro** [comment]
Branch `1.2` should work on Plone 4.3 but this keyword isn't working. @jensens could you please revert https://github.com/plone/plone.app.robotframework/commit/9f80a05edceb71ae91e6da4dc69d353f4763863c?

@mauritsvanrees gforcada FYI

**Comment by mauritsvanrees** [comment]
I have trouble following the versions reported here. Let me check for myself.

- Plone 4.3.18 pins plone.app.robotframework 1.2.0.
- Plone 4.3.19 pins plone.app.robotframework 1.2.3.
- Plone coredev buildout used plone.app.robotframework branch 1.2.x.
- Plone 5.0.10 and 5.1.4+ use version 1.3.1 or higher.
- Core Plone in 4.3 does not use this keyword, so it is not affected.

Seems like a valid bug report, and should be safe to revert the change. I will make a PR.
Pinning plone.app.robotframework back to 1.2.0 seems a valid workaround in case someone is in a hurry.

**Comment by idgserpro** [comment]
> Core Plone in 4.3 does not use this keyword, so it is not affected.

@mauritsvanrees thanks for fix! It looks like Travis has detected this error. See:

https://travis-ci.org/plone/plone.app.robotframework/jobs/392447680#L528

However, @gforcada  removed `.travis.yml` in https://github.com/plone/plone.app.robotframework/commit/ebeeba3675a2cb629e65019c1203109997f39f30

Maybe it's a good idea to bring it back.
