### ISSUE TITLE
Use plone.api for content keywords.

### ISSUE THREAD

**Issue by tisto** [plone/plone.app.robotframework#32]
@datakurre You removed plone.api as a dependency, right? Is the old code still available? What if we would submit a PLIP to allow plone.api in the core for testing purposes and then re-introduce plone.api? After that I would like us to think about ways to make the full plone.api available for robot keywords.

**Comment by jensens** [comment]
Old, issue, I close this one, reopen if you think it worth to follow up here: 

This would probably introduce a circular dependency, so -1 on this. First we need to get our dependency mess in Plone core cleaned up, and I dont see this happen soon.
