### ISSUE TITLE
CSS media-queries not working with phantomjs and robottests

### ISSUE THREAD

**Issue by fkubis** [plone/plone.app.robotframework#37]
In combination of robottests and headless-browser, which is phantomjs in my case, css media-queries like ```@media only screen and (min-width: 641px){}``` not working.

Example running this test:

    *** Settings ***
    
    Resource  keywords.robot
    
    Library  Remote  ${PLONE_URL}/RobotRemote
    
    Suite Setup  Setup
    Suite Teardown  Teardown
    
    
    *** Test Cases ***
    
    Test Error Template
        Go to  ${PLONE_URL}/thisisdefinatlynotexistent
        Capture Page Screenshot
        Page Should Contain Element  css=.error-page
    
    
    *** Keywords ***
    
    Setup
        Open test browser
        Set Window Size  1024  768
        Force language  en
    
    Teardown
        Close all browsers

The screenshot shows the mobile version of our website. The mobile theme shows, cause the used css-framework is mobile first.
If I run this little phantomjs browser script, at the same environment

	var page = require('webpage').create();
	page.viewportSize = {
	  width: 1024,
	  height: 768
	};
	page.open('http://localhost:8080/MyPage', function(status) {
	  console.log("Status: " + status);
	  if(status === "success") {
	    page.render('foo.png');
	  }
	  phantom.exit();
	}); 

The screenshot show the correct desktop version. After playing with some colors, I am sure that the phantomjs-browser ignores CSS media-queries in combination with robot-tests.

**Comment by datakurre** [comment]
@fkubis Is the size of the resulting screenshot from your robot still 1024 x 768, even when it displays mobile layout?

Technically, this may be more of an issue of Ghostdriver (PhantomJS' built-in driver for Selenium, which powers robot framework acceptance tests).

**Comment by fkubis** [comment]
@datakurre yes the resulting screenshot is 1024 x 768

We switched to an headless firefox as an workaround. Looks like phantomjs and webkit are to old.
