### ISSUE TITLE
"Create content" fails when creating a New Item on a site which uses archetypes default content types and other dexterity content types

### ISSUE THREAD

**Issue by gotcha** [plone/plone.app.robotframework#41]
Checking for `HAS_DEXTERITY` is over simplified, we should check if the types of the default content types are `Products.ATContentTypes` or `plone.app.contenttypes`

Because the check is failing, when trying to create an image for News Item, we use the wrong code path.
 
And we get an `AssertionError: 'NamedImage' object has no attribute 'seek'`.

**Comment by datakurre** [comment]
Agreed. Actually, we should check FTI type for the given portal_type.
