### ISSUE TITLE
Upgrade to robotframework 3.0?

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.robotframework#51]
[robotframework 3.0](https://pypi.python.org/pypi/robotframework/3.0) has been released; should we upgrade?

**Comment by thet** [comment]
Currently testing such an upgrade, including other (most importantly Selenium) here:
https://github.com/plone/buildout.coredev/pull/157
and here
https://github.com/plone/bobtemplates.plone/pull/115

**Comment by datakurre** [comment]
:+1: If you get no issues. I only recently returned to work, but initially all the latest versions have worked.
