### ISSUE TITLE
New release and new branch 0.9.x?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.robotframework#61]
I can make a release, but fine if someone else does it.
I propose the following:
- Merge my two minor pull requests of today (pull #59 and #60). [edit: done myself]
- Temporarily revert the part of my earlier pull request #57 that removes the `run_on_failure`: it works wonders on Plone coredev, but may be too invasive in a bugfix release. We do keep the new `Plone Test Setup` and `Plone Test Teardown` keywords.
- Release this as 0.9.17 and create maintenance branch 0.9.x.
- Revert the temporary revert of `run_on_failure` on master branch.
- Release 1.0. Use that in coredev 4.3 and higher.

**Comment by mauritsvanrees** [comment]
I have executed the above plan.

**Comment by datakurre** [comment]
@mauritsvanrees Thanks a lot for taking care of all this!
