### ISSUE TITLE
Would it be the case to pin robotframework-wavelibrary in versions.cfg?

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.robotframework#64]
Since you're already have "good pins" in https://github.com/plone/plone.app.robotframework/blob/22ca0ba4d32a14eef625289b2620b83a2e1f179c/versions.cfg for a bunch of robotframework addons, would it be the case to add robotframework-wavelibrary as well?

Another question: on Plone's release version file (http://dist.plone.org/release/4.3.11/versions.cfg), we have more pinned addons for robot testing:

```cfg
plone.app.robotframework = 1.0
robotframework = 3.0
robotframework-debuglibrary = 0.4
robotframework-ride = 1.5.2.1
robotframework-selenium2library = 1.7.4
robotframework-selenium2screenshots = 0.7.0
robotsuite = 1.7.0
selenium = 2.53.5
sphinx-rtd-theme = 0.1.5
sphinxcontrib-robotframework = 0.5.1
```

Where exactly do they come from? It's more complete than versions.cfg from plone.app.robotframework.

We're asking this because we're pinning https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg after plone pinnings in [collective.cover](https://github.com/collective/collective.cover/issues/672) and other packages in [plonegovbr](https://github.com/plonegovbr/), but we started to think if it's really necessary.

**Comment by gforcada** [comment]
@idgserpro I think that the ones in buildout.coredev are more up to date (and are kept more up to date), but it can not harm to add some extra pins.

Adding a pin does not mean that is required, so it should  be no harm on it.

As for extending a versions.cfg from a master branch (which I would not recommend), I would rather add that on buildout.coredev itself, or better if that's only for your own needs, pin it locally.

**Comment by datakurre** [comment]
@idgserpro Please, provide a pull request with added and updated pins.

I would not make a bit issue of that we have versions both in p.a.robotframework repository and buildout.coredev. You could choose the one that fits better for you, and then participate maintaining the one you use.

**Comment by datakurre** [comment]
@idgserpro But I have bad news about wavelibrary:

* At first, I merged it into robotframework-selenium2accessibility already a long time ago with also a colorcontrastchecker add-on. Although, the packaged extension version is probably still the same.

* Unfortunately, the Firefox extension used in wavelibrary have been http://wave.webaim.org/toolbar/ discontinued and the library is probably already broken with current Firefox versions.

Luckily, EU will have new accessibility directive soon ("in two years"), so hopefully I'd be able to return maintaining those packages in the near future...

**Comment by idgserpro** [comment]
> I would not make a bit issue of that we have versions both in p.a.robotframework repository and buildout.coredev

We don't mind too, we just wanted to know the motivation: why the difference between this package pinning and coredev? This way we could choose which one fits better for us. We're not saying we *should* have just one pinning, we just want to understand *why*.

@datakurre We didn't know about this situation in wavelibrary. I think this issue can be closed then.

**Comment by gforcada** [comment]
@idgserpro as a general rule of thumb, the pins on buildout.coredev are usually more up to date, in case of doubt you can always open an issue on buildout.coredev or Products.CMFPlone about it

**Comment by idgserpro** [comment]
It's still useful to pin your https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg if you're still supporting Plone 4.2: in http://dist.plone.org/release/4.2-latest/versions.cfg, the robots infra-structure isn't pinned.
