### ISSUE TITLE
Create user with roles

### ISSUE THREAD

**Issue by ksuess** [plone/plone.app.robotframework#77]
1. `Create user  siteadmin  Contributor  Reviewer  Site Administrator`
2. `Create user  siteadmin2  roles=('Contributor','Reviewer','Site Administrator')`

None of the two creates a user as expected.

1. creates a user with roles ('Member',)
2. creates a user with roles ('Contributor','Reviewer','Site Administrator'), missing role 'Member'

**Comment by datakurre** [comment]
Fixed in #78
